config/routes.rb
Frescobol::Application.routes.draw do
  

  resources :mixes do
   resources :tracks

  end

  get "home/index"

 root :to => 'home#index'

end

app/models/mix.rb
class Mix < ActiveRecord::Base
  attr_accessible :autor, :nome
  
  has_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :mix
  attr_accessible :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  # GET /mixes
  # GET /mixes.json
  def index
    @mixes = Mix.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixes }
    end
  end

  # GET /mixes/1
  # GET /mixes/1.json
  def show
    @mix = Mix.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/new
  # GET /mixes/new.json
  def new
    @mix = Mix.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/1/edit
  def edit
    @mix = Mix.find(params[:id])
  end

  # POST /mixes
  # POST /mixes.json
  def create
    @mix = Mix.new(params[:mix])

    respond_to do |format|
      if @mix.save
        format.html { redirect_to @mix, notice: 'Mix was successfully created.' }
        format.json { render json: @mix, status: :created, location: @mix }
      else
        format.html { render action: "new" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixes/1
  # PUT /mixes/1.json
  def update
    @mix = Mix.find(params[:id])

    respond_to do |format|
      if @mix.update_attributes(params[:mix])
        format.html { redirect_to @mix, notice: 'Mix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix = Mix.find(params[:id])
    @mix.destroy

    respond_to do |format|
      format.html { redirect_to mixes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  #after_filter:get_real_url, only => [:edit, :create]
  def create
      @mix = Mix.find(params[:mix_id])
      @track = @mix.tracks.create(params[:track])
      redirect_to mix_path(@mix)
   end
   
  def edit
    @mix = Mix.find(params[:mix_id])
    @track = @mix.tracks.find(params[:id])
  end
  
  def destroy
    @mix = Mix.find(params[:mix_id])
    @track = @mix.tracks.find(params[:id])
    @track.destroy
    redirect_to mix_path(@mix)
  end
  
  def get_real_url
    # @set_url = @track.url
    # s = "Player.getRealUrl("+@set_url+");"
     # render :update do|page|
     # page <<  s

  end

    

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p id="sm">Criando <%= link_to "Meus mixes", mixes_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Frescobol :: Umas frescuras com SoundCloud</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "http://connect.soundcloud.com/sdk.js" %>

  	<%= csrf_meta_tags %>
	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
  </head>
<head>
  
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Frescobol</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Descubra Mixes", mixes_path %></li>
          <li><%= link_to "Adicione um Mix", new_mix_path() %></li>
        </ul>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid">
	<div class="row-fluid">
		<div class="span8"><%= yield %></div>
		<div class="span4">
			<div class="well sidebar-nav">
			<h2>Frescobol <small>o que é essa frescura</small></h2>
			<p>Frescobol é um projeto de brincadeira para aprender:</p>
			<ul>
				<li>A API do Soundcloud</li>
				<li>Usar o SoundManager2</li>
				<li>Usar o Bootstrap </li>
				<li>Me ambientar com Rails</li>
			</ul>
			<p> Na versão atual,o Frescobol é capaz de adicionar tracks por urls do Soundcloud</p>
			</div>
		</div>
	</div>
</div>
</body>
</html>

         

app/views/mixes/_form.html.erb
<%= form_for @mix, :html => {:class =>"form-horizontal"} do |f| %>
  <% if @mix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mix.errors.count, "error") %> prohibited this mix from being saved:</h2>

      <ul>
      <% @mix.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar"%>
  </div>
<% end %>

  

app/views/mixes/edit.html.erb
<h1>Editando mix</h1>

<%= render 'form' %>

<%= link_to 'Show', @mix %> |
<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<h1>Lista de Mixes</h1>
<div class="row">
<div class="span7">
		<table class="table table-striped">
		  <tr>
		    <th class="span2">Nome</th>
		    <th class="span2">Autor</th>
		    <th class="span2"></th>
		  </tr>
		
		<% @mixes.each do |mix| %>
		  <tr>
		    <td><%= link_to mix.nome, mix_path(mix) %> </td>
		    <td><%= mix.autor %></td>
		     <td align="right">
          	 <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mix_path(mix), :class => 'btn btn-mini' %>
          	 <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mix_path(mix),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        	</td>
      		</tr>
		 
		<% end %>
		</table>
		
		<br />
		
		<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mix_path,
            :class => 'btn btn-primary' %>
</div>
</div>

app/views/mixes/new.html.erb
<h1>Novo mix</h1>

<%= render 'form' %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<script> var myTracks=["http://soundcloud.com/radioguidance/hardboiled-blues-kid-who-remix","http://soundcloud.com/radioguidance/gyraxiom-feat-bernardo-ramos"];</script>
<p id="notice"><%= notice %></p>

<h1>Mix  <%= @mix.nome %> <small>por <%= @mix.autor %> </h1>
<div class="row">
<div class="span7">
	<h2> Tocar Mix</h2>
	<a href="#" id="frescobolPlayer" >Tocar</a>
	<h2> Tracks no Mix</h2>
	<table class="table table-striped">
		  <tr>
		    <th class="span2">id</th>
		    <th class="span2">URL</th>
		<!--     <th class="span2"></th> -->
		  </tr>
		
		<% @mix.tracks.each do |track| %>
		  <tr>
		    <td><%= track.id %></td>
		    <td><%= track.url %></td>
		     <!-- <td align="right">
          	 <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_track_path(track), :class => 'btn btn-mini' %>
          	 <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      track_path(track),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        	</td> -->
      		</tr>
		 
		<% end %>
		</table>
	
	
	
	
<h2> Adcionar Track</h2>	
<%= render "tracks/form" %>

</div>
</div>

<%= link_to 'Editar', edit_mix_path(@mix) %> |
<%= link_to 'Voltar', mixes_path %>

app/views/tracks/_form.html.erb
<%= form_for([@mix, @mix.tracks.build]) do |f| %>
 
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar"%>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<div class="row">
<div class="span7">
		<table class="table table-striped">
		  <tr>
		    <th class="span2">id</th>
		    <th class="span2">URL</th>
		    <th class="span2"></th>
		  </tr>
		
		<% @tracks.each do |mix| %>
		  <tr>
		    <td><%= track.id %></td>
		    <td><%= track.url %></td>
		     <td align="right">
          	 <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_track_path(track), :class => 'btn btn-mini' %>
          	 <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      track_path(track),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        	</td>
      		</tr>
		 
		<% end %>
		</table>
		

</div>
</div>

app/views/tracks/new.html.erb
<h1>Novo track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @track.url %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>